# Bài 1

In [9]:
#A
n = 15

res_a = (3**(n+1)-1)/(3-1)
print(res_a)

#B
n = 15
res_b = ((((10**(n+1))-1)/9) - (n+1))/9
print(res_b)

21523360.0
123456790123455.0


# Bài 2

In [10]:
import random

def check_prime(x):
    check = 1
    if x<2:
        check = 0
        return check

    for i in range(2,x):
        if x%i == 0:
            check = 0
            break
    return check
        
def func(x):
    arr = []
    for i in range(x):
        temp = random.randint(1,1000)
        arr.append(temp)
    print('Array:',sorted(arr))

    max = 0
    for j in arr:
        if (check_prime(j) == 1) and (j >= max):
            max = j
    print('Số nguyên tố lớn nhất:',max)
            

func(20)



Array: [2, 3, 98, 332, 358, 492, 515, 578, 587, 649, 687, 700, 716, 717, 755, 781, 800, 818, 947, 992]
Số nguyên tố lớn nhất: 947


# Bài 3

In [11]:
import numpy as np

a = np.array([[0,0,0,0,0],[0,1,1,0,0],[0,1,1,0,0],[0,0,1,0,0],[0,0,0,0,0]])
c = np.array([[0,0,0,0,0],[0,1,1,0,0],[0,1,1,0,0],[0,0,1,0,0],[0,0,0,0,0]])
print(a)
print('-'*40)
for i in range(0,3):
    for j in range(0,3):
        b = a[i:i+3,j:j+3]
        status = np.sum(b)

        if status == 3 or status == 4:
            c[i+1,j+1] = 1
        else:
            c[i+1,j+1] = 0   

print(c)

[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 1 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
----------------------------------------
[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 0 0 1 0]
 [0 1 1 0 0]
 [0 0 0 0 0]]
